syntax = "proto3";

package course.v1;

option go_package = "github.com/Nikita-Filonov/api-go-autotests-server/gen/go/v1;v1";

import "v1/common.proto";

message CreateUserRequest {
  string email = 1;
  string password = 2;
  string last_name = 3;
  string first_name = 4;
  string middle_name = 5;
}

message UpdateUserRequest {
  string id = 1;
  optional string email = 2;
  optional string last_name = 3;
  optional string first_name = 4;
  optional string middle_name = 5;
}

message GetUserRequest { string id = 1; }
message GetUserResponse { User user = 1; }

service UsersService {
  rpc CreateUser(CreateUserRequest) returns (GetUserResponse);
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc GetMe(Empty) returns (GetUserResponse);
  rpc UpdateUser(UpdateUserRequest) returns (GetUserResponse);
  rpc DeleteUser(GetUserRequest) returns (Empty);
}
